/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.selvinchuquiej.view;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import org.selvinchuquiej.controller.CrearCuentaController;
import org.selvinchuquiej.controller.RetirosController;
import org.selvinchuquiej.model.Cuenta;
import org.selvinchuquiej.model.Transaccion;
import org.selvinchuquiej.system.Principal;
import org.selvinchuquiej.system.Ventana;

/**
 *
 * @author Selvi
 */
public class RetirosView extends javax.swing.JFrame implements Ventana {

    /**
     * Creates new form RetirosView
     */
    private Principal principal;
    private Transaccion transaccion;
    private CrearCuentaController crearCuentaController;
    private RetirosController retirosController;

    public RetirosView() {
    }

    public RetirosView(Principal principal, CrearCuentaController crearCuentaController, RetirosController retirosController) {
        this.principal = principal;
        this.crearCuentaController = crearCuentaController;
        this.retirosController = retirosController;
        initComponents();
    }

    public void cargarCuentas() {
        retirosController.cargarCuenta(cmbCuentas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbCuentas = new javax.swing.JComboBox<>();
        btnAceptarRetiro = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtMontoRetiro = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jLabel1.setText("Cuenta");

        jLabel3.setText("Monto");

        btnAceptarRetiro.setText("Aceptar");
        btnAceptarRetiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarRetiroActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 40)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Retiros");

        txtMontoRetiro.setText("0");
        txtMontoRetiro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMontoRetiroKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegresar)
                .addContainerGap(319, Short.MAX_VALUE))
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnAceptarRetiro)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbCuentas, 0, 300, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMontoRetiro))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnRegresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtMontoRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnAceptarRetiro)
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        principal.mostrarPrincipalView();
        this.ocultar();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnAceptarRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarRetiroActionPerformed
        // TODO add your handling code here:

        try {
            String detalle = "Retiro";
            double montoDebitado = Double.parseDouble(txtMontoRetiro.getText());

            Cuenta cuenta = retirosController.cuentaActual(cmbCuentas);
            if (cuenta != null) {
                double saldoActual = cuenta.getSaldo();
                if (montoDebitado <= 0) {
                    JOptionPane.showMessageDialog(null, "El monto a retirar debe ser mayor a 0");
                } else if (montoDebitado > saldoActual) {
                    JOptionPane.showMessageDialog(null, "Saldo Insuficiente");
                } else {
                    Transaccion depositoNew = new Transaccion(cuenta, detalle, montoDebitado, 0, cuenta.getSaldo());
                    retirosController.crearRetiro(depositoNew);
                    System.out.println(retirosController.retiros);
                    JOptionPane.showMessageDialog(null, "Retiro realizado correctamente");
                    retirosController.cargarCuenta(cmbCuentas);
                }
            } else {
                System.out.println("El monto no puede ser 0");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Porfavor ingresa un monto valido para retirar");
            txtMontoRetiro.setText("");
        }
    }//GEN-LAST:event_btnAceptarRetiroActionPerformed

    private void txtMontoRetiroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMontoRetiroKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if ((caracter < '0' || caracter > '9') && caracter != '.' && (caracter != KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtMontoRetiroKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RetirosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RetirosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RetirosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RetirosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RetirosView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarRetiro;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<Cuenta> cmbCuentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtMontoRetiro;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mostrar() {
        setVisible(true);
    }

    @Override
    public void ocultar() {
        setVisible(false);
    }
}
